### ISSUE TITLE
What should be in SERVER env variable for localhost zookeeper work?

### ISSUE THREAD

**Issue by ghost** [mesoscloud/zookeeper#4]
Hello,
I try to launch mesos, zookeeper and marathon on localhost.

Can you help to setup docker containers properly?

``` sh
-e SERVERS=node-1,node-2,node-3 \
```

should be

``` sh
-e SERVERS=localhost \
```

?

**Comment by pekermert** [comment]
Hi, this code from entrypoint.sh so it seems variable should be IP or DNS record. 
`python -c "print '\n'.join(['server.%i=%s:2888:3888' % (i + 1, x) for i, x in enumerate('$SERVERS'.split(','))])" >> /opt/zookeeper/conf/zoo.cfg`
